development:
  adapter: postgresql
  database: fdornas_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fdornas_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fdornas_production
  pool: 5
  timeout: 5000